In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('demanda_stock_insumos_cancer_gastrico_sintetico.csv')

In [6]:
df.describe()

,semana,mes,anio,ocupacion_deseada,ocupacion_albergue,capacidad_albergue,porcentaje_ocupacion,pacientes_total,pacientes_prioridad_baja,pacientes_prioridad_media,...,stock_cierre,consumo_diario,consumo_lag_1,consumo_lag_7,consumo_promedio_7d,consumo_promedio_14d,demanda_7_dias,demanda_14_dias,stock_proyectado_7d,stock_proyectado_14d
count,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000,5010.0,5010.000000,5010.000000,5010.00000,5010.000000,...,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000,5010.000000
mean,28.077844,6.907186,2025.122754,74.155689,74.155689,100.0,0.741557,74.155689,21.00000,26.880240,...,295.876647,16.906786,16.891218,16.839321,16.853008,16.779940,119.251896,239.783633,193.531537,72.999800
std,14.668627,3.355607,0.328188,14.268331,14.268331,0.0,0.142683,14.268331,5.86737,5.901266,...,256.647281,17.544943,17.501343,17.380649,16.303281,16.002907,115.739019,229.291558,217.877237,223.587378
min,1.000000,1.000000,2025.000000,50.000000,50.000000,100.0,0.500000,50.000000,8.00000,12.000000,...,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-247.000000,-625.000000
25%,17.000000,4.000000,2025.000000,62.000000,62.000000,100.0,0.620000,62.000000,17.00000,23.000000,...,128.000000,3.000000,3.000000,3.000000,3.000000,3.000000,21.000000,43.000000,66.000000,-17.000000
50%,29.000000,7.000000,2025.000000,74.000000,74.000000,100.0,0.740000,74.000000,20.00000,27.000000,...,193.000000,9.000000,9.000000,9.000000,12.000000,12.000000,84.000000,172.000000,128.000000,67.000000
75%,41.000000,10.000000,2025.000000,86.000000,86.000000,100.0,0.860000,86.000000,25.00000,31.000000,...,372.000000,29.000000,29.000000,29.000000,25.860000,26.000000,182.750000,371.750000,224.000000,137.750000
max,52.000000,12.000000,2026.000000,100.000000,100.000000,100.0,1.000000,100.000000,40.00000,40.000000,...,1468.000000,86.000000,85.000000,85.000000,69.140000,66.570000,512.000000,964.000000,1248.000000,989.000000

In [11]:
df.shape

(5010, 51)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5010 entries, 0 to 5009
Data columns (total 51 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   fecha                             5010 non-null   object
 1   dia_semana                        5010 non-null   object
 2   semana                            5010 non-null   int64
 3   mes                               5010 non-null   int64
 4   anio                              5010 non-null   int64
 5   ocupacion_deseada                 5010 non-null   int64
 6   ocupacion_albergue                5010 non-null   int64
 7   capacidad_albergue                5010 non-null   int64
 8   porcentaje_ocupacion              5010 non-null   float64
 9   pacientes_total                   5010 non-null   int64
 10  pacientes_prioridad_baja          5010 non-null   int64
 11  pacientes_prioridad_media         5010 non-null   int64
 12  pacientes_prioridad_alta          5010 non-null   int64
 13  pacientes_estadio_0_I             5010 non-null   int64
 14  pacientes_estadio_II              5010 non-null   int64
 15  pacientes_estadio_III_IV          5010 non-null   int64
 16  pacientes_quimioterapia           5010 non-null   int64
 17  pacientes_cirugia                 5010 non-null   int64
 18  pacientes_paliativos              5010 non-null   int64
 19  pacientes_soporte_nutricional     5010 non-null   int64
 20  pacientes_con_anemia              5010 non-null   int64
 21  pacientes_con_vomitos             5010 non-null   int64
 22  pacientes_dolor_alto              5010 non-null   int64
 23  pacientes_desnutricion            5010 non-null   int64
 24  pacientes_quimio_curativa         5010 non-null   int64
 25  pacientes_quimio_avanzada         5010 non-null   int64
 26  pacientes_flot_estimado           5010 non-null   int64
 27  pacientes_folfox_capox_estimado   5010 non-null   int64
 28  pacientes_her2_positivo_estimado  5010 non-null   int64
 29  item_id                           5010 non-null   object
 30  item_nombre                       5010 non-null   object
 31  categoria_item                    5010 non-null   object
 32  tipo_stock                        5010 non-null   object
 33  unidad_medida                     5010 non-null   object
 34  stock_actual                      5010 non-null   int64
 35  stock_minimo                      5010 non-null   int64
 36  ingresos_stock                    5010 non-null   int64
 37  salidas_stock                     5010 non-null   int64
 38  stock_cierre                      5010 non-null   int64
 39  consumo_diario                    5010 non-null   int64
 40  consumo_lag_1                     5010 non-null   float64
 41  consumo_lag_7                     5010 non-null   float64
 42  consumo_promedio_7d               5010 non-null   float64
 43  consumo_promedio_14d              5010 non-null   float64
 44  demanda_7_dias                    5010 non-null   int64
 45  demanda_14_dias                   5010 non-null   int64
 46  stock_proyectado_7d               5010 non-null   int64
 47  stock_proyectado_14d              5010 non-null   int64
 48  stock_critico_7d                  5010 non-null   object
 49  stock_critico_14d                 5010 non-null   object
 50  stock_critico                     5010 non-null   object
dtypes: float64(5), int64(36), object(10)
memory usage: 1.9+ MB

In [9]:
df.isnull().sum()

fecha                               0
dia_semana                          0
semana                              0
mes                                 0
anio                                0
ocupacion_deseada                   0
ocupacion_albergue                  0
capacidad_albergue                  0
porcentaje_ocupacion                0
pacientes_total                     0
pacientes_prioridad_baja            0
pacientes_prioridad_media           0
pacientes_prioridad_alta            0
pacientes_estadio_0_I               0
pacientes_estadio_II                0
pacientes_estadio_III_IV            0
pacientes_quimioterapia             0
pacientes_cirugia                   0
pacientes_paliativos                0
pacientes_soporte_nutricional       0
pacientes_con_anemia                0
pacientes_con_vomitos               0
pacientes_dolor_alto                0
pacientes_desnutricion              0
pacientes_quimio_curativa           0
pacientes_quimio_avanzada           0
pacientes_flot_estimado             0
pacientes_folfox_capox_estimado     0
pacientes_her2_positivo_estimado    0
item_id                             0
item_nombre                         0
categoria_item                      0
tipo_stock                          0
unidad_medida                       0
stock_actual                        0
stock_minimo                        0
ingresos_stock                      0
salidas_stock                       0
stock_cierre                        0
consumo_diario                      0
consumo_lag_1                       0
consumo_lag_7                       0
consumo_promedio_7d                 0
consumo_promedio_14d                0
demanda_7_dias                      0
demanda_14_dias                     0
stock_proyectado_7d                 0
stock_proyectado_14d                0
stock_critico_7d                    0
stock_critico_14d                   0
stock_critico                       0
dtype: int64

In [15]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5005    False
5006    False
5007    False
5008    False
5009    False
Length: 5010, dtype: bool

In [19]:
# IQR outlier detection for all numeric columns

outlier_summary = []

for col in numeric_df.columns:
    q1 = numeric_df[col].quantile(0.25)
    q3 = numeric_df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    
    outliers = (numeric_df[col] < lower_bound) | (numeric_df[col] > upper_bound)
    outlier_summary.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": outliers.sum()
    })

outliers_df = pd.DataFrame(outlier_summary).sort_values("outlier_count", ascending=False)
print(outliers_df)

# Rows with at least one outlier in any numeric column
outlier_mask = pd.Series(False, index=numeric_df.index)

for col in numeric_df.columns:
    q1 = numeric_df[col].quantile(0.25)
    q3 = numeric_df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outlier_mask |= (numeric_df[col] < lower_bound) | (numeric_df[col] > upper_bound)

outlier_rows = df.loc[outlier_mask]
print("Number of rows with at least one outlier:", outlier_rows.shape[0])
outlier_rows.head()

                              column  lower_bound  upper_bound  outlier_count
40              stock_proyectado_14d     -249.125      369.875            874
39               stock_proyectado_7d     -171.000      461.000            657
2                               anio     2025.000     2025.000            615
31                      stock_cierre     -238.000      738.000            450
27                      stock_actual     -269.500      806.500            385
29                    ingresos_stock        0.000        0.000            360
28                      stock_minimo     -100.000      300.000            334
37                    demanda_7_dias     -221.625      425.375             92
35               consumo_promedio_7d      -31.290       60.150             91
36              consumo_promedio_14d      -31.500       60.500             89
38                   demanda_14_dias     -450.125      864.875             81
30                     salidas_stock      -36.000       68.000             33
32                    consumo_diario      -36.000       68.000             33
33                     consumo_lag_1      -36.000       68.000             32
26  pacientes_her2_positivo_estimado       -3.500        8.500             30
34                     consumo_lag_7      -36.000       68.000             30
8           pacientes_prioridad_baja        5.000       37.000             30
20              pacientes_dolor_alto        5.500       33.500             15
19             pacientes_con_vomitos       10.000       50.000             15
15                 pacientes_cirugia       16.500       68.500             15
21            pacientes_desnutricion        2.500       30.500             15
11             pacientes_estadio_0_I        5.000       37.000             15
1                                mes       -5.000       19.000              0
0                             semana      -19.000       77.000              0
3                  ocupacion_deseada       26.000      122.000              0
7                    pacientes_total       26.000      122.000              0
6               porcentaje_ocupacion        0.260        1.220              0
5                 capacidad_albergue      100.000      100.000              0
4                 ocupacion_albergue       26.000      122.000              0
24           pacientes_flot_estimado       -2.500       17.500              0
23         pacientes_quimio_avanzada        2.000       26.000              0
22         pacientes_quimio_curativa        9.000       49.000              0
16              pacientes_paliativos        0.500       20.500              0
9          pacientes_prioridad_media       11.000       43.000              0
10          pacientes_prioridad_alta        4.500       48.500              0
12              pacientes_estadio_II        6.500       42.500              0
17     pacientes_soporte_nutricional       21.500       81.500              0
18              pacientes_con_anemia       20.500       80.500              0
13          pacientes_estadio_III_IV        6.500       50.500              0
14           pacientes_quimioterapia       12.000       60.000              0
25   pacientes_folfox_capox_estimado        8.000       48.000              0
Number of rows with at least one outlier: 1888

,fecha,dia_semana,semana,mes,anio,ocupacion_deseada,ocupacion_albergue,capacidad_albergue,porcentaje_ocupacion,pacientes_total,...,consumo_lag_7,consumo_promedio_7d,consumo_promedio_14d,demanda_7_dias,demanda_14_dias,stock_proyectado_7d,stock_proyectado_14d,stock_critico_7d,stock_critico_14d,stock_critico
17,2025-03-31,lunes,14,3,2025,52,52,100,0.52,52,...,7.0,11.71,8.00,28,121,268,175,no,no,no
43,2025-04-26,sabado,17,4,2025,64,64,100,0.64,64,...,7.0,10.86,11.57,50,114,254,190,no,no,no
66,2025-05-19,lunes,21,5,2025,66,66,100,0.66,66,...,8.0,8.14,10.29,129,175,123,77,no,no,no
70,2025-05-23,viernes,21,5,2025,70,70,100,0.70,70,...,9.0,7.14,11.43,96,168,170,98,no,no,no
85,2025-06-07,sabado,23,6,2025,66,66,100,0.66,66,...,8.0,10.29,12.00,54,164,203,93,no,no,no

In [20]:
# Preprocesamiento de atípicos con IQR: capeo por columna numérica

numeric_df = df.select_dtypes(include=[np.number]).copy()
df_preprocesado = df.copy()
outlier_summary = []

for col in numeric_df.columns:
    q1 = numeric_df[col].quantile(0.25)
    q3 = numeric_df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_mask = (df_preprocesado[col] < lower_bound) | (df_preprocesado[col] > upper_bound)
    outlier_count = outlier_mask.sum()

    df_preprocesado[col] = df_preprocesado[col].clip(lower=lower_bound, upper=upper_bound)

    outlier_summary.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": int(outlier_count)
    })

outliers_df = pd.DataFrame(outlier_summary).sort_values("outlier_count", ascending=False)
print("Resumen de atípicos antes del capeo:")
print(outliers_df)

print("\nForma original:", df.shape)
print("Forma procesada:", df_preprocesado.shape)
print("\nVista previa del dataset preprocesado:")
df_preprocesado.head()

Resumen de atípicos antes del capeo:
                              column  lower_bound  upper_bound  outlier_count
40              stock_proyectado_14d     -249.125      369.875            874
39               stock_proyectado_7d     -171.000      461.000            657
2                               anio     2025.000     2025.000            615
31                      stock_cierre     -238.000      738.000            450
27                      stock_actual     -269.500      806.500            385
29                    ingresos_stock        0.000        0.000            360
28                      stock_minimo     -100.000      300.000            334
37                    demanda_7_dias     -221.625      425.375             92
35               consumo_promedio_7d      -31.290       60.150             91
36              consumo_promedio_14d      -31.500       60.500             89
38                   demanda_14_dias     -450.125      864.875             81
30                     salidas_stock      -36.000       68.000             33
32                    consumo_diario      -36.000       68.000             33
33                     consumo_lag_1      -36.000       68.000             32
26  pacientes_her2_positivo_estimado       -3.500        8.500             30
34                     consumo_lag_7      -36.000       68.000             30
8           pacientes_prioridad_baja        5.000       37.000             30
20              pacientes_dolor_alto        5.500       33.500             15
19             pacientes_con_vomitos       10.000       50.000             15
15                 pacientes_cirugia       16.500       68.500             15
21            pacientes_desnutricion        2.500       30.500             15
11             pacientes_estadio_0_I        5.000       37.000             15
1                                mes       -5.000       19.000              0
0                             semana      -19.000       77.000              0
3                  ocupacion_deseada       26.000      122.000              0
7                    pacientes_total       26.000      122.000              0
6               porcentaje_ocupacion        0.260        1.220              0
5                 capacidad_albergue      100.000      100.000              0
4                 ocupacion_albergue       26.000      122.000              0
24           pacientes_flot_estimado       -2.500       17.500              0
23         pacientes_quimio_avanzada        2.000       26.000              0
22         pacientes_quimio_curativa        9.000       49.000              0
16              pacientes_paliativos        0.500       20.500              0
9          pacientes_prioridad_media       11.000       43.000              0
10          pacientes_prioridad_alta        4.500       48.500              0
12              pacientes_estadio_II        6.500       42.500              0
17     pacientes_soporte_nutricional       21.500       81.500              0
18              pacientes_con_anemia       20.500       80.500              0
13          pacientes_estadio_III_IV        6.500       50.500              0
14           pacientes_quimioterapia       12.000       60.000              0
25   pacientes_folfox_capox_estimado        8.000       48.000              0

Forma original: (5010, 51)
Forma procesada: (5010, 51)

Vista previa del dataset preprocesado:

,fecha,dia_semana,semana,mes,anio,ocupacion_deseada,ocupacion_albergue,capacidad_albergue,porcentaje_ocupacion,pacientes_total,...,consumo_lag_7,consumo_promedio_7d,consumo_promedio_14d,demanda_7_dias,demanda_14_dias,stock_proyectado_7d,stock_proyectado_14d,stock_critico_7d,stock_critico_14d,stock_critico
0,2025-03-14,viernes,11,3,2025,51,51,100,0.51,51,...,22.0,22.00,22.00,64.0,110.0,196,150.0,no,no,no
1,2025-03-15,sabado,11,3,2025,50,50,100,0.50,50,...,22.0,22.00,22.00,48.0,115.0,190,123.0,no,no,no
2,2025-03-16,domingo,11,3,2025,52,52,100,0.52,52,...,22.0,20.00,20.00,30.0,112.0,190,108.0,no,no,no
3,2025-03-17,lunes,12,3,2025,56,56,100,0.56,56,...,22.0,20.67,20.67,29.0,111.0,169,87.0,no,no,no
4,2025-03-18,martes,12,3,2025,56,56,100,0.56,56,...,22.0,17.50,17.50,32.0,112.0,158,78.0,no,no,no

In [21]:
# Técnica 2: Valores negativos a cero en columnas de stock

print("\n=== TÉCNICA 2: Tratar Valores Negativos ===")
stock_cols = ['stock_actual', 'stock_minimo', 'stock_cierre', 'stock_proyectado_7d', 'stock_proyectado_14d']
consumo_cols = [col for col in df_preprocesado.columns if 'consumo' in col.lower() or 'demanda' in col.lower()]

print(f"Columnas de stock: {stock_cols}")
print(f"Columnas de consumo/demanda: {consumo_cols}")

# Reemplazar negativos por 0 en stocks
for col in stock_cols:
    if col in df_preprocesado.columns:
        negativos = (df_preprocesado[col] < 0).sum()
        if negativos > 0:
            print(f"  {col}: {negativos} valores negativos → 0")
            df_preprocesado[col] = df_preprocesado[col].clip(lower=0)

# Reemplazar negativos por 0 en consumo/demanda
for col in consumo_cols:
    if col in df_preprocesado.columns:
        negativos = (df_preprocesado[col] < 0).sum()
        if negativos > 0:
            print(f"  {col}: {negativos} valores negativos → 0")
            df_preprocesado[col] = df_preprocesado[col].clip(lower=0)

print("✓ Valores negativos tratados")

=== TÉCNICA 2: Tratar Valores Negativos ===
Columnas de stock: ['stock_actual', 'stock_minimo', 'stock_cierre', 'stock_proyectado_7d', 'stock_proyectado_14d']
Columnas de consumo/demanda: ['consumo_diario', 'consumo_lag_1', 'consumo_lag_7', 'consumo_promedio_7d', 'consumo_promedio_14d', 'demanda_7_dias', 'demanda_14_dias']
  stock_proyectado_7d: 352 valores negativos → 0
  stock_proyectado_14d: 1407 valores negativos → 0
✓ Valores negativos tratados

In [22]:
# Técnica 5: Feature Engineering (creación de variables derivadas)

print("\n=== TÉCNICA 5: Feature Engineering ===")

df_features = df_preprocesado.copy()

# Ratio stock actual / stock mínimo
df_features['ratio_stock_minimo'] = (df_features['stock_actual'] / (df_features['stock_minimo'] + 1)).fillna(0)

# Cobertura: stock actual / consumo diario (cuántos días de stock hay)
df_features['dias_cobertura'] = (df_features['stock_actual'] / (df_features['consumo_diario'] + 1)).fillna(0)

# Diferencia entre ingresos y salidas
df_features['neto_movimiento'] = df_features['ingresos_stock'] - df_features['salidas_stock']

# Variabilidad del consumo (consumo promedio 7d vs consumo diario)
df_features['variabilidad_consumo'] = (abs(df_features['consumo_diario'] - df_features['consumo_promedio_7d']) / (df_features['consumo_promedio_7d'] + 1)).fillna(0)

# Porcentaje de ocupación del albergue como proxy de demanda
df_features['es_ocupacion_alta'] = (df_features['porcentaje_ocupacion'] > df_features['porcentaje_ocupacion'].median()).astype(int)

# Volumen de pacientes con alta prioridad
df_features['ratio_pacientes_alta_prioridad'] = (df_features['pacientes_prioridad_alta'] / (df_features['pacientes_total'] + 1)).fillna(0)

print("Variables derivadas creadas:")
print(f"  - ratio_stock_minimo: stock actual / stock mínimo")
print(f"  - dias_cobertura: días de stock disponible")
print(f"  - neto_movimiento: ingresos - salidas")
print(f"  - variabilidad_consumo: variabilidad del consumo")
print(f"  - es_ocupacion_alta: flag de ocupación alta")
print(f"  - ratio_pacientes_alta_prioridad: proporción de pacientes prioritarios")

print(f"\nForma con nuevas features: {df_features.shape}")
print("\nEsta adísticas de las nuevas variables:")
print(df_features[['ratio_stock_minimo', 'dias_cobertura', 'variabilidad_consumo']].describe())

=== TÉCNICA 5: Feature Engineering ===
Variables derivadas creadas:
  - ratio_stock_minimo: stock actual / stock mínimo
  - dias_cobertura: días de stock disponible
  - neto_movimiento: ingresos - salidas
  - variabilidad_consumo: variabilidad del consumo
  - es_ocupacion_alta: flag de ocupación alta
  - ratio_pacientes_alta_prioridad: proporción de pacientes prioritarios

Forma con nuevas features: (5010, 57)

Esta adísticas de las nuevas variables:
       ratio_stock_minimo  dias_cobertura  variabilidad_consumo
count         5010.000000     5010.000000           5010.000000
mean             2.753219       42.447678              0.486524
std              0.896129       69.874580              0.647047
min              1.230769        1.936170              0.000000
25%              2.065462       11.806784              0.118161
50%              2.679402       21.651515              0.300699
75%              3.318182       44.805556              0.610895
max              5.660714      806.500000              6.512953

In [24]:
df.shape

(5010, 51)